// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import dotenv from "dotenv"
import { defineConfig } from "prisma/config"

// Next.jsの.env.localを優先して読み込む
dotenv.config({ path: ".env.local", override: true })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
